apiVersion: apps/v1
kind: Deployment
metadata:
  name: wmstats-prod
  namespace: {{ .Values.namespace }}
  labels:
    app: wmstats
    track: prod
spec:
  replicas: {{ .Values.numReplicas }}
  selector:
    matchLabels:
      app: wmstats
      track: prod
  template:
    metadata:
      labels:
        app: wmstats
        track: prod
    spec:
      containers:
      - name: wmstats-prod
        image: {{ .Values.imageName }}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 10m
