apiVersion: v1
kind: Service
metadata:
  name: wmstats-prod
  namespace: {{ .Values.namespace }}
  labels:
    app: wmstats
    track: prod
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: wmstats
    track: prod

